### ISSUE TITLE
Prepare a user guide for running llama2 on TPU {v5e, v4}, GPU {L4, H100} 

### ISSUE THREAD

**Issue by miladm** [pytorch-tpu/transformers#37]
Prepare a user guide for running llama2 on TPU {v5e, v4}, GPU {L4, H100}. Please merge the guide to the following branch.

https://github.com/pytorch-tpu/transformers/tree/llama2-google-next-training

**Comment by miladm** [comment]
cc @manfeibai re: GPU related documentation.

**Comment by kevint324** [comment]
is there any updates on GPU documentation with pytorch 2.1? thanks

@miladm  @ManfeiBai

**Comment by alanwaketan** [comment]
The SPMD user guide is here: https://github.com/pytorch-tpu/transformers/blob/llama2-google-next-training/SPMD_USER_GUIDE.md

**Comment by alanwaketan** [comment]
> is there any updates on GPU documentation with pytorch 2.1? thanks
> 
> @miladm @ManfeiBai

No, the experiment here is primarily focusing on TPU SPMD.
